add get_mac and get_ip methods
InsaLan/langate3000 pull request #27
Opened 2024-10-16 18:38 UTC by Ecnama

## Description

Add Arp class containing arp-related methods:
- get_mac(ip) 
- get_ip(mac)

2024-10-18 06:14 UTC, KwikKill commented on netcontrol/arp.py
> +        f = open('/proc/net/arp', 'r') # Open arp table
You never close the file, it's better to user `with open(...) as f:` to prevent resources waste.

2024-10-18 06:14 UTC, KwikKill commented on netcontrol/arp.py
> +                ip = line.split(" ")[0] # 41 is the position of the MAC address in the line
wrong comment :wink:

2024-10-18 11:29 UTC, SkytAsul approved these changes

2024-10-18 20:51 UTC, pixup1 approved these changes
lgtm 🚀🚀🚀

2024-10-19 19:48 UTC, SkytAsul approved these changes

2024-10-19 19:52 UTC, SkytAsul requested changes

2024-10-19 19:52 UTC, SkytAsul commented on netcontrol/arp.py
> +            return {"error": "MAC not found"}
Renvoyer une exception plutôt. Dans ce cas, une 404.

2024-10-19 19:52 UTC, SkytAsul commented on netcontrol/arp.py
> +            return {"error": "IP not found"}
404

2024-10-21 11:14 UTC, SkytAsul commented on netcontrol/main.py
> +    return arp.get_ip(mac)
Il faut que le paramètre de la fonction Python ait le même nom que le paramètre dans le chemin de la route.

2024-10-21 19:22 UTC, SkytAsul approved these changes
Let's gong

2024-10-21 20:33 UTC, KwikKill approved these changes
LGTM

2024-10-21 20:34 UTC, merged