Enable backend/netcontrol communication
InsaLan/langate3000 pull request #30
Opened 2024-10-18 18:19 UTC by Ecnama

## Description

This PR enables the backend to send requests to the netcontrol API via http.

## Checklist

- [ ] I have tested the changes locally and they work as expected.
- [ ] I have tested the responsiveness of the changes and they work as expected.
- [ ] I have assigned the pull request to the appropriate reviewer(s).
- [ ] I have added labels to the pull request, if necessary.

2024-10-19 14:14 UTC, SkytAsul commented
Besoin de review maintenant ou bien la PR n'est pas terminée ?

2024-10-19 16:03 UTC, Ecnama commented
Alors en théorie c'est terminé, mais les tests passent pas donc je les ai mal modifié j'imagine

2024-10-19 16:11 UTC, SkytAsul commented
Fix tout est quand c'est bon, marque la PR comme "ready for review"

2024-10-19 20:08 UTC, SkytAsul requested changes
En plus de tout ça, à tous les endroits où une méthode de netcontrol est appelée (i.e. `netcontrol.connect_user(...)` il faut wrap dans un _try-except HTTPError_ et gérer les erreurs correctement.

2024-10-19 20:08 UTC, SkytAsul commented on backend/langate/modules/netcontrol.py
> +class Netcontrol:
Dans cette classe, stocke aussi un champ "REQUEST_URL" avec  `http://{self.HOST_IP}:6784`. Ça évitera d'avoir ce truc de dupliqué à 5 endroits différents qui nous causera la misère si jamais un jour on change le port/le protocole.

2024-10-19 20:08 UTC, SkytAsul commented on backend/langate/modules/netcontrol.py
> +        super().__init__(self.message)
Le système d'erreur n'est plus pareil. Il faut supprimer cette classe trop générique.

2024-10-19 20:08 UTC, SkytAsul commented on backend/langate/modules/netcontrol.py
> +                raise RequestError(response.json()["error"])
On utilisera les erreurs HTTP. Remplacer ces lignes par `response.raise_for_status()` qui lèvera automatiquement une `HTTPError` si jamais netcontrol a renvoyé une erreur 4xx ou 5xx.

2024-10-27 20:52 UTC, SkytAsul commented
Oula y'a un soucis de branches de base là

2024-11-08 09:40 UTC, SkytAsul approved these changes

2024-11-08 11:03 UTC, SkytAsul approved these changes

2024-11-08 11:05 UTC, merged