Add nftables methods to netcontrol
InsaLan/langate3000 pull request #32
Opened 2024-10-18 23:48 UTC by pixup1

## Description

This adds basic device management functions to netcontrol using nftables.

## Checklist

- [ ] I have tested the changes locally and they work as expected.
- [ ] I have tested the responsiveness of the changes and they work as expected.
- [ ] I have assigned the pull request to the appropriate reviewer(s).
- [ ] I have added labels to the pull request, if necessary.

## Related Issues

#19

2024-10-19 14:13 UTC, SkytAsul requested changes

2024-10-19 14:13 UTC, SkytAsul commented on netcontrol/nft.py
> +        return pat in str(data)
Y'a pas mieux si c'est pour check si la MAC est dans une map ? Là c'est un peu lourd et si la MAC est dans une autre rule (pour une raison quelconque) ça va faire un faux positif.

2024-10-19 14:13 UTC, SkytAsul commented on netcontrol/nft.py
> +    def connect_user(self, mac: str = "", mark: int = 101, name: str = ""):
Pourquoi mettre 101 par défaut ? IMO ne rien mettre c'est mieux, pour laisser le backend gérer les données par défaut.

2024-10-19 14:13 UTC, SkytAsul commented on netcontrol/nft.py
> +            self.logger.error(f"Tried to connect device {mac} (name: {name}) with incorrect mark {mark}")
Et du coup on fait comment pour faire passer un appareil hors des tunnels ? Comme pour le commentaire précédent, je suis d'avis de laisser le backend gérer.

2024-10-19 14:14 UTC, SkytAsul commented
Ça a été testé sinon ?

2024-10-19 15:55 UTC, pixup1 commented on netcontrol/nft.py
> +    def connect_user(self, mac: str = "", mark: int = 101, name: str = ""):
Ça va causer une erreur par défaut du coup

2024-10-19 16:10 UTC, SkytAsul commented on netcontrol/nft.py
> +    def connect_user(self, mac: str = "", mark: int = 101, name: str = ""):
Cf le commentaire suivant

2024-10-19 19:55 UTC, SkytAsul requested changes
J'avais oublié ça dans ma review.

2024-10-19 19:55 UTC, SkytAsul commented on netcontrol/nft.py
> +            return {"error": "Device was not previously connected"}
Renvoyer une erreur HTTP. Dans ce cas, une 400.

2024-10-19 19:55 UTC, SkytAsul commented on netcontrol/nft.py
> +            return {"error": "Device was not previously connected"}
Idem, une 400 ici

2024-10-19 21:00 UTC, pixup1 commented on netcontrol/nft.py
> +        return pat in str(data)
le mieux c'est de pas le faire en fait haha

2024-10-19 21:02 UTC, pixup1 commented
> Ça a été testé sinon ?

J'ai testé la map, l'ajout et la suppresion d'appareils. Mais les règles je vois pas trop comment faire.

2024-10-19 21:05 UTC, SkytAsul requested changes

2024-10-19 21:05 UTC, SkytAsul commented on netcontrol/nft.py
> +            raise HTTPException(status_code=404, detail="Unexpected nftables error occurred")
Pas une 404 mais une 500. Ce n'est pas le backend qui s'est chié dessus : c'est netcontrol qui n'arrive pas à traiter la requête pour une raison inconnue.

2024-10-19 21:05 UTC, SkytAsul commented on netcontrol/nft.py
> +            name = "previously_connected_device"
Pourquoi ?

2024-10-19 21:08 UTC, pixup1 commented on netcontrol/nft.py
> +            raise HTTPException(status_code=404, detail="Unexpected nftables error occurred")
k

2024-10-19 21:09 UTC, pixup1 commented on netcontrol/nft.py
> +            name = "previously_connected_device"
Si on change la mark avec set_mark, le nom est pas donné. L'alternative c'est de créer un dictionnaire de macs et de noms mais sachant que tfaçon ça sert qu'au logging, bof.

2024-10-20 08:34 UTC, SkytAsul commented on netcontrol/nft.py
> +            name = "previously_connected_device"
Ah déso je pensais qu'on stockait le nom de l'utilisateur dans la map aussi, à la manière du "comment" dans ipset. Il se trouve que ce n'est pas possible.

2024-10-20 08:35 UTC, SkytAsul approved these changes

2024-10-20 08:37 UTC, SkytAsul commented
> > Ça a été testé sinon ?
> 
> J'ai testé la map, l'ajout et la suppresion d'appareils. Mais les règles je vois pas trop comment faire.

Lance le docker netcontrol sur la tête et avec curl, envoie des requêtes HTTP qui vont simuler le backend. Et du coup vérifie si
1. si tu n'est pas co à la gate, pas accès à Internet
2. les requêtes HTTP sont redirigées vers gate.insalan.fr
3. après connexion, tu as accès à Internet

2024-10-20 17:36 UTC, SkytAsul commented on netcontrol/main.py
> +    return nft.set_mark(mac, mark)
Il faut une certaine cohérence dans les routes. Soit tu mets un paramètre "mac" dans la route partout, soit nulle part

2024-10-20 17:39 UTC, pixup1 commented on netcontrol/main.py
> +    return nft.set_mark(mac, mark)
My bad j'aurais pas du tout copier coller

2024-10-21 06:07 UTC, Ecnama approved these changes
lgtm ;;)

2024-10-21 12:06 UTC, SkytAsul requested changes

2024-10-21 19:20 UTC, SkytAsul approved these changes
Let's gooooooo

2024-10-21 21:04 UTC, KwikKill approved these changes
Overall good PR but some small nitpicks on the variable class.

2024-10-21 21:11 UTC, KwikKill commented on netcontrol/variables.py
> +        with open("/variables.json", "r") as file:
Oh, mb, I swapped the outside and the inside mount location. It's good :ok_hand:

2024-10-21 21:11 UTC, pixup1 commented on netcontrol/variables.py
> +        with open("/variables.json", "r") as file:
Wouldn't that raise an error anyway ?

2024-10-21 21:12 UTC, pixup1 commented on netcontrol/variables.py
> +        with open("/variables.json", "r") as file:
In the docker compose even ?

2024-10-21 21:18 UTC, KwikKill commented on netcontrol/variables.py
> +        with open("/variables.json", "r") as file:
Yes, you're right, we can rely on default error handling. The application will restart endlessly until fixed tho.

2024-10-21 21:21 UTC, pixup1 commented on netcontrol/variables.py
> +        with open("/variables.json", "r") as file:
Tbh I'd rather have that than rely on a default value, that would make troubleshooting very hard

2024-10-21 21:26 UTC, KwikKill commented on netcontrol/variables.py
> +        with open("/variables.json", "r") as file:
seems faire :ok_hand:

2024-10-21 21:31 UTC, merged