Limit API access
InsaLan/langate3000 pull request #38
Opened 2024-10-25 11:58 UTC by Ecnama

## Description

Forbids outside access to the API by binding Fastapi to the docker bridge IP.

## Checklist

- [ ] I have tested the changes locally and they work as expected.
- [ ] I have tested the responsiveness of the changes and they work as expected.
- [ ] I have assigned the pull request to the appropriate reviewer(s).
- [ ] I have added labels to the pull request, if necessary.

2024-10-25 12:06 UTC, pixup1 commented on netcontrol/fastapi_init.py
Y'a des fois où bash c'est mieux quand même xD

2024-10-25 12:08 UTC, Ecnama commented on netcontrol/fastapi_init.py
Pas faux, j'aime pas trop bash, mais je peux le refaire, ce sera plus propre

2024-11-11 18:45 UTC, pixup1 requested changes
Use an nftable at launch to limit interaction to loaclhost addresses only. Scrap the bash script.

2024-11-14 11:58 UTC, pixup1 approved these changes
✨✨ 🄻🅶🅃🅼 ✨✨

2024-11-14 12:10 UTC, merged